# Fly.io Configuration for ReddyFit Photo Analysis API
# Learn more: https://fly.io/docs/reference/configuration/

app = "reddyfit-api"
primary_region = "iad"  # Washington D.C. (Ashburn, VA)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  APP_ENV = "production"
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Scale to 0 when not in use (free tier)
  max_machines_running = 2   # Max instances for scaling

  # Health check configuration
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

  # Readiness check (Kubernetes-style)
  [[http_service.checks]]
    grace_period = "5s"
    interval = "15s"
    method = "GET"
    timeout = "3s"
    path = "/api/health/ready"

# Machine configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # 1GB RAM

# Persistent storage (optional, for caching)
# Commented out for now - enable if you need persistent cache
# [[mounts]]
#   source = "reddyfit_cache"
#   destination = "/app/cache"
#   initial_size = "1gb"

# Auto-scaling based on load
[metrics]
  port = 9091
  path = "/metrics"

# Secrets (set via flyctl secrets set)
# Required secrets:
#   ANTHROPIC_API_KEY
#   FIREBASE_PROJECT_ID
#   FIREBASE_STORAGE_BUCKET
#   FIREBASE_CREDENTIALS_PATH (or embed credentials as JSON string)

# Optional secrets:
#   SENTRY_DSN
#   OPENAI_API_KEY
